npm install tonejs-instrument-flute
npm install tonejs-instrument-trumpet-mp3
npm install tonejs-instrument-guitar-electric-mp3
npm install tonejs-instrument-piano-mp3
npm install tonejs-instrument-violin-mp3
npm install tonejs-instrument-bass-electric-mp3
npm install tonejs-instrument-bassoon-mp3
npm install tonejs-instrument-cello-mp3
npm install tonejs-instrument-clarinet-mp3
npm install tonejs-instrument-contrabass-mp3
npm install tonejs-instrument-flute-mp3
npm install tonejs-instrument-french-horn-mp3
npm install tonejs-instrument-guitar-acoustic-mp3
npm install tonejs-instrument-guitar-nylon-mp3
npm install tonejs-instrument-harmonium-mp3
npm install tonejs-instrument-harp-mp3
npm install tonejs-instrument-organ-mp3
npm install tonejs-instrument-saxophone-mp3
npm install tonejs-instrument-trombone-mp3
npm install tonejs-instrument-tuba-mp3
npm install tonejs-instrument-xylophone-mp3
npm install tonejs-instrument-bass-electric-ogg
npm install tonejs-instrument-bass-electric-wav
npm install tonejs-instrument-bassoon-ogg
npm install tonejs-instrument-bassoon-wav
npm install tonejs-instrument-xylophone
npm install tonejs-instrument-xylophone-ogg
npm install tonejs-instrument-xylophone-wav
npm install tonejs-instrument-bass-electric
npm install tonejs-instrument-violin
npm install tonejs-instrument-cello-ogg
npm install tonejs-instrument-clarinet-ogg
npm install tonejs-instrument-cello-wav
npm install tonejs-instrument-contrabass-ogg
npm install tonejs-instrument-clarinet-wav
npm install tonejs-instrument-flute-ogg
npm install tonejs-instrument-contrabass-wav
npm install tonejs-instrument-french-horn-ogg
npm install tonejs-instrument-flute-wav
npm install tonejs-instrument-french-horn-wav
npm install tonejs-instrument-guitar-acoustic-ogg
npm install tonejs-instrument-guitar-electric-ogg
npm install tonejs-instrument-guitar-electric-wav
npm install tonejs-instrument-guitar-nylon-ogg
npm install tonejs-instrument-guitar-acoustic-wav
npm install tonejs-instrument-guitar-nylon-wav
npm install tonejs-instrument-harmonium-ogg
npm install tonejs-instrument-harp-ogg
npm install tonejs-instrument-harp-wav
npm install tonejs-instrument-harmonium-wav
npm install tonejs-instrument-organ-ogg
npm install tonejs-instrument-organ-wav
npm install tonejs-instrument-piano-ogg
npm install tonejs-instrument-saxophone-ogg
npm install tonejs-instrument-trombone-ogg
npm install tonejs-instrument-saxophone-wav
npm install tonejs-instrument-trumpet-ogg
npm install tonejs-instrument-piano-wav
npm install tonejs-instrument-trombone-wav
npm install tonejs-instrument-trumpet-wav
npm install tonejs-instrument-tuba-ogg
npm install tonejs-instrument-tuba-wav
npm install tonejs-instrument-violin-ogg
npm install tonejs-instrument-violin-wav
